/**
 * Keys at rest.
 *
 * A person's Hedera key is generated by this server and lives in the
 * database, sealed under one key-encryption key from the environment. AES-256
 * in GCM mode through Web Crypto: a fresh nonce per seal and the tag checked
 * on open, so a row that was edited, swapped or read under another key
 * refuses to open rather than yielding a wrong key. The KEK itself never
 * touches the database, and a dump of the database alone holds nothing that
 * signs.
 */

export interface Keystore {
  /** Reverses `seal`. Throws on a wrong key, altered bytes or a foreign format. */
  readonly open: (sealed: string) => Promise<string>;
  readonly seal: (plaintext: string) => Promise<string>;
}

export class KeystoreError extends Error {
  readonly kind = "KeystoreError";

  constructor(message: string) {
    super(message);
    this.name = "KeystoreError";
  }
}

const VERSION = "v1";
const NONCE_BYTES = 12;
const KEY_BYTES = 32;

/** Base64 into a fresh, plain `ArrayBuffer`-backed array, which is what Web Crypto takes. */
const bytesOf = (base64: string): Uint8Array<ArrayBuffer> => {
  const decoded = Buffer.from(base64, "base64");
  const bytes = new Uint8Array(decoded.length);
  bytes.set(decoded);
  return bytes;
};

const decodeKek = (kekBase64: string): Uint8Array<ArrayBuffer> => {
  const bytes = bytesOf(kekBase64.trim());
  if (bytes.length !== KEY_BYTES) {
    throw new KeystoreError(
      `The key-encryption key must be ${KEY_BYTES} bytes in base64; this one decodes to ${bytes.length}.`
    );
  }
  return bytes;
};

/** One keystore per KEK. The key is imported once and never exported again. */
export const aesGcmKeystore = (kekBase64: string): Keystore => {
  const key = crypto.subtle.importKey(
    "raw",
    decodeKek(kekBase64),
    { name: "AES-GCM" },
    false,
    ["encrypt", "decrypt"]
  );
  return {
    open: async (sealed) => {
      const [version, nonce, body, extra] = sealed.split(".");
      if (
        version !== VERSION ||
        nonce === undefined ||
        body === undefined ||
        extra !== undefined
      ) {
        throw new KeystoreError("Not a value this keystore sealed.");
      }
      let plain: ArrayBuffer;
      try {
        plain = await crypto.subtle.decrypt(
          { iv: bytesOf(nonce), name: "AES-GCM" },
          await key,
          bytesOf(body)
        );
      } catch {
        throw new KeystoreError(
          "The sealed value did not open: a different key, or altered bytes."
        );
      }
      return new TextDecoder().decode(plain);
    },
    seal: async (plaintext) => {
      const nonce = crypto.getRandomValues(new Uint8Array(NONCE_BYTES));
      const cipher = await crypto.subtle.encrypt(
        { iv: nonce, name: "AES-GCM" },
        await key,
        new TextEncoder().encode(plaintext)
      );
      return [
        VERSION,
        Buffer.from(nonce).toString("base64"),
        Buffer.from(cipher).toString("base64"),
      ].join(".");
    },
  };
};
