import {
  ApprovalId,
  ReceiptId,
  Trade,
  TradeId,
  TradeStepId,
} from "@froggy/domain";
import { Schema } from "effect";

export const tradeFixture = (key: string): Trade =>
  Schema.decodeUnknownSync(Trade)({
    v: 1,
    events: [],
    id: TradeId.generate(),
    idempotencyKey: key,
    connectionId: null,
    createdAt: 1,
    updatedAt: 1,
    revision: 0,
    input: {
      network: "eip155:8453",
      venue: "uniswap",
      action: "swap",
      wallet: `0x${"1".repeat(40)}`,
      tokenIn: `0x${"2".repeat(40)}`,
      tokenOut: `0x${"3".repeat(40)}`,
      amount: "100",
      position: null,
      slippageBps: 50,
      maxNativeFee: "10",
    },
    inputFingerprint: "a".repeat(64),
    status: "awaiting_approval",
    expectedOutput: "200",
    minimumOutput: "199",
    actualOutput: null,
    phase: "standard",
    steps: [
      {
        id: TradeStepId.generate(),
        kind: "swap",
        description: "Fixture swap",
        payload: {
          kind: "evm",
          to: `0x${"4".repeat(40)}`,
          data: "0x",
          value: "0",
          gasLimit: "1",
          maxFeePerGas: "1",
          maxPriorityFeePerGas: "0",
          nonce: 1,
        },
        fingerprint: "b".repeat(64),
        expiresAt: 100_000,
        simulation: {
          status: "passed",
          provider: "fixture",
          observedAt: 1,
          block: "1",
          gasUnits: "1",
          assetChanges: [],
          error: null,
          stubbed: true,
        },
        status: "awaiting_approval",
        approvalId: ApprovalId.generate(),
        authorizedAt: null,
        ruleId: null,
        transactionId: null,
        signedPayload: null,
        submittedAt: null,
        confirmedAt: null,
        actualNativeFee: null,
        error: null,
      },
    ],
    reservations: [],
    reservationState: "none",
    receiptId: ReceiptId.generate(),
    error: null,
    limitations: [],
    stubbed: true,
  });
